-- Run only in a disposable migrated database. No probability-based flaky assertions.
begin;
create function public.chance_assert(ok boolean, message text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'Assertion failed: %',message; end if; end $$;
select public.chance_assert((select win_chance=20 from public.game_settings),'Default winning chance is 20%');
insert into auth.users(id,email) values('12000000-0000-4000-8000-000000000001','chance-admin@example.invalid'),('12000000-0000-4000-8000-000000000002','chance-attendee@example.invalid');
select public.provision_question_admin('12000000-0000-4000-8000-000000000001');
insert into public.game_prizes(id,name,quantity,active) values('22000000-0000-4000-8000-000000000001','Cap',5,true);
set local role anon;
select public.chance_assert((select win_chance=20 from public.game_settings),'Public may read odds');
do $$ begin
 begin update public.game_settings set win_chance=100; raise exception 'Public changed odds'; exception when insufficient_privilege then null; end;
 begin perform * from public.game_attempts; raise exception 'Public read attempts'; exception when insufficient_privilege then null; end;
end $$;
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','12000000-0000-4000-8000-000000000002',true);
update public.game_settings set win_chance=100;
select public.chance_assert((select win_chance=20 from public.game_settings),'Non-admin cannot change odds');
select set_config('request.jwt.claim.sub','12000000-0000-4000-8000-000000000001',true);
update public.game_settings set win_chance=0;
select public.chance_assert((select win_chance=0 from public.game_settings),'Admin can set odds');
do $$ begin
 begin update public.game_settings set win_chance=101; raise exception 'Over 100 accepted'; exception when check_violation then null; end;
 begin update public.game_settings set win_chance=-1; raise exception 'Negative chance accepted'; exception when check_violation then null; end;
end $$;
reset role;
set local role service_role;
select public.chance_assert(public.spin_game('32000000-0000-4000-8000-000000000001','Ada','ada@example.invalid',repeat('a',64))->>'outcome'='no_prize','0% always records a loss');
select public.chance_assert((select count(*)=0 from public.game_wins),'Loss does not create winner');
select public.chance_assert((select quantity=5 from public.game_prizes),'Loss leaves stock unchanged');
select public.chance_assert((select outcome='no_prize' and prize_id is null and prize_name is null and win_chance=0 from public.game_attempts),'Loss persists details and odds');
select public.chance_assert((select wheel->0->>'id'='no-prize' and jsonb_array_length(wheel)=1 from public.game_attempts),'0% wheel has only a no-prize segment');
update public.game_settings set win_chance=100;
select public.chance_assert(public.spin_game('32000000-0000-4000-8000-000000000001','Ada','ada@example.invalid',repeat('b',64))->>'outcome'='no_prize','Retry after odds/IP change returns original loss');
select public.chance_assert(public.spin_game(gen_random_uuid(),'Ada','ADA@example.invalid',repeat('b',64))->>'error'='This email has already been used to spin. One attempt per email address.','Losing email cannot retry with new request');
select public.chance_assert(public.spin_game(gen_random_uuid(),'Bola','bola@example.invalid',repeat('a',64))->>'error'='Someone has already spun from this network. One attempt per IP address.','Losing IP cannot retry with another email');
select public.chance_assert((select count(*)=1 from public.game_attempts),'Blocked retries create no new attempts');
select public.chance_assert(public.spin_game('32000000-0000-4000-8000-000000000002','Bola','bola@example.invalid',repeat('b',64))->>'outcome'='won','100% always awards available stock');
select public.chance_assert((select quantity=4 from public.game_prizes),'Winning draw decrements stock once');
select public.chance_assert((select count(*)=1 from public.game_wins),'Winning draw remains in winner records');
select public.chance_assert((select a.id=w.id from public.game_attempts a join public.game_wins w using(request_id)),'Winner reference matches attempt');
update public.game_settings set win_chance=20;
select public.spin_game('32000000-0000-4000-8000-000000000003','Chidi','chidi@example.invalid',repeat('c',64));
select public.chance_assert((select win_chance=20 and jsonb_array_length(wheel)=2 and (wheel->0->>'weight')::numeric=20 and (wheel->1->>'weight')::numeric=80 from public.game_attempts where email='chidi@example.invalid'),'20% draw saves proportional wheel and odds');
select public.chance_assert((select count(*)=3 from public.game_attempts),'Either random outcome records exactly one attempt');
update public.game_prizes set quantity=0;
select public.chance_assert(public.spin_game(gen_random_uuid(),'Dara','dara@example.invalid',repeat('d',64)) ? 'error','No stock rejects draw');
select public.chance_assert((select count(*)=3 from public.game_attempts),'No-stock error does not consume attempt');
reset role;
select public.chance_assert((select count(*)=3 from private.game_ip_attempts),'Wins and losses both claim IPs');
set local role authenticated;
select set_config('request.jwt.claim.sub','12000000-0000-4000-8000-000000000002',true);
select public.chance_assert((select count(*)=0 from public.game_attempts),'Non-admin cannot read attempts');
select set_config('request.jwt.claim.sub','12000000-0000-4000-8000-000000000001',true);
select public.chance_assert((select count(*)=3 from public.game_attempts),'Admin sees all outcomes');
rollback;
